update email route
AMPnet/identity-service pull request #5
Opened 2021-07-01 13:00 UTC by josipkoncurat

2021-07-01 14:31 UTC, domagojlatecki approved these changes

2021-07-05 09:46 UTC, githinho requested changes

2021-07-05 09:46 UTC, githinho commented on src/main/kotlin/com/ampnet/identityservice/controller/UserController.kt
Add route: `@GetMapping("/user")` which returns User data: address: String and email: String?

2021-07-05 09:46 UTC, githinho commented on src/main/kotlin/com/ampnet/identityservice/controller/UserController.kt
> +    fun updateEmail(@RequestBody emailRequest: EmailRequest): ResponseEntity<Unit> {
Return user data (address and updated email).

2021-07-05 09:46 UTC, githinho commented on src/main/kotlin/com/ampnet/identityservice/service/impl/UserServiceImpl.kt
> +    override fun updateEmail(email: String, address: String) {
Return user.

2021-07-05 12:40 UTC, githinho approved these changes

2021-07-05 12:45 UTC, merged